"""fix_alerts_zscore_precision_and_null_unique

Revision ID: 9e08c81c3bf2
Revises: d2775c46f6fc
Create Date: 2026-05-21 15:52:34.196027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e08c81c3bf2'
down_revision: Union[str, None] = 'd2775c46f6fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'z_score',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=False)
    op.drop_constraint('uq_alert_account_date_scope_service', 'alerts', type_='unique')
    op.create_unique_constraint('uq_alert_account_date_scope_service', 'alerts', ['aws_account_id', 'alert_date', 'scope', 'service_name'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_alert_account_date_scope_service', 'alerts', type_='unique')
    op.create_unique_constraint('uq_alert_account_date_scope_service', 'alerts', ['aws_account_id', 'alert_date', 'scope', 'service_name'])
    op.alter_column('alerts', 'z_score',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
