"""create aws_credentials table

Revision ID: bc3b9192f3fa
Revises: 68bc81c19996
Create Date: 2026-05-26 16:12:14.107057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc3b9192f3fa'
down_revision: Union[str, None] = '68bc81c19996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aws_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_key_id_encrypted', sa.Text(), nullable=False),
    sa.Column('secret_access_key_encrypted', sa.Text(), nullable=False),
    sa.Column('access_key_last4', sa.String(length=4), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aws_credentials_user_id'), 'aws_credentials', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aws_credentials_user_id'), table_name='aws_credentials')
    op.drop_table('aws_credentials')
    # ### end Alembic commands ###
