"""create_alerts_table

Revision ID: d2775c46f6fc
Revises: a43602f90740
Create Date: 2026-05-21 15:42:16.798429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2775c46f6fc'
down_revision: Union[str, None] = 'a43602f90740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aws_account_id', sa.Integer(), nullable=False),
    sa.Column('alert_date', sa.Date(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('service_name', sa.String(length=256), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('baseline_mean', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('z_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='new', nullable=False),
    sa.Column('notified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aws_account_id'], ['aws_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aws_account_id', 'alert_date', 'scope', 'service_name', name='uq_alert_account_date_scope_service')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    # ### end Alembic commands ###
